//Strip whitespace from the begining and end of a string.
String.prototype.trim = function() {
    return this.replace(/^[ ]+|[ ]+$/g, '');
}

//Make a object representing a production rule from text.
function parseProduction(text) {
    var production = {};
    var rules = text.trim().split("\n");

    for (var i = 0; i < rules.length && rules[i] != ""; i++) {
        rules[i] = rules[i].split("->")
        //Left handside of a rightarrow "->" in a rule "alpha -> beta gamma".
        var LHS = rules[i][0].trim();
        //Right handside of a rightarrow ... 
        var RHS = rules[i][1].split(" ");

        //Add to production
        if (production[LHS] == undefined) production[LHS] = [];
        production[LHS].push(RHS);
    }
    return production;
}

//from a object generated by parseProduction to string.
function syntaxToString(syntax) {
    var str = "";
    for (var rule in syntax)
        for (var i = 0; i < syntax[rule].length; i++)
        str += rule + " -> " + syntax[rule][i].join(" ") + "\n";
    return str;
}