(require 'cl)

(defun replace-variables (variable-list replace-with)
  (let ((variable-list (sort variable-list '(lambda (a b)  (> (car (cdr a)) (car (cdr b))))))
	(cursor-position (point)))
    (dolist (variable variable-list)
      (let ((left (car (cdr variable)))
	    (right (car (cdr (cdr variable)))))
      (delete-region left right)
      (goto-char left)
      (insert replace-with)))
    (goto-char cursor-position)))
      
(defun cursor-is-on-variable (cursor-position variable)
  (and (<= (car (cdr variable)) cursor-position)
       (>= (car (cdr (cdr variable))) cursor-position)))

(defun get-variable-pointed-by-cursor (cursor-position variable-map)
  (let ((reference (car variable-map))
	(declaration (cdr variable-map))
	result)
    (dolist (variable reference result)
      (let ((refer-from (car variable))
	    (refer-to (cdr variable)))
	(if (cursor-is-on-variable cursor-position refer-from)
	    (setq result refer-from)
	  (if (cursor-is-on-variable cursor-position refer-to)
	      (setq result refer-to)))))
    (unless result 
      (dolist (variable declaration result)
	(if (cursor-is-on-variable cursor-position variable)
	    (setq result variable))))
    result))
    
(defun enumerate-variables-to-replace (variable-map pointed)
  (let* ((reference (car variable-map))
	(declaration (cdr variable-map))
	variable-positions
	(decl (let (result)
		(or 
		 (dolist (variable declaration result)
		   (if (equal variable pointed)
		       (setq result variable)))
		 (dolist (variable reference result)
		   (let ((refer-from (car variable))
			 (refer-to (cdr variable)))
		     (if (equal refer-from pointed)
			 (setq result refer-to))))))))
    (setq variable-positions (cons decl variable-positions))
    (dolist (variable reference variable-positions)
		   (let ((refer-from (car variable))
			 (refer-to (cdr variable)))
		     (if (equal refer-to decl)
			 (setq variable-positions
			       (cons refer-from variable-positions)))))))
		      

(defun refer-variable (env variable-name)
  (unless env (throw 'error "variable not found"))
  (if (equal (car (car env)) variable-name)
      (car env)
    (refer-variable (cdr env) variable-name)))

(defun make-variable-map (ast)
  (let ((reference nil)
	(declaration nil))
    (scope ast (list))
    (cons reference declaration)))

(defun scope (ast env)
  (let ((class (car ast)))
    (cond
     ((eq class 'int) nil)
     ((eq class 'str) nil)
     ((eq class 'app)
      (let ((func (car (cdr ast)))
	    (arg (car (cdr (cdr ast)))))
      (scope func env)
      (scope arg env)))
     ((eq class 'var)
      (let* ((variable (car (cdr ast)))
	     (variable-name (car variable))
	     (refer-to (refer-variable env variable-name)))
	(setq reference (cons 
			    (cons variable refer-to)
			    reference))))
     ((eq class 'abs)
      (let ((variable (car (cdr ast)))
	    (body (car (cdr (cdr ast)))))
	(setq declaration (cons variable declaration))
	(scope body (cons variable env))))
     ((eq class 'let)
      (let* ((variable (car (cdr ast)))
	     (bind-expr (car (cdr (cdr ast))))
	     (body (car (cdr (cdr (cdr ast))))))
	(setq declaration (cons variable declaration))
	(scope bind-expr env)
	(scope body (cons variable env)))))))


(provide 'my-expr-rename)
