(require 'my-expr-data-structure)

(setq pop-count [1 1 1 4 1 2 1 1 1 3 5 2 0 4 ])

(setq token-to-index '((ID . 0)
(INT . 1)
(STRING . 2)
(FN . 3)
(LP . 4)
(LET . 5)
(start . 6)
(exp . 7)
(appexp . 8)
(atexp . 9)
(VAL . 10)
(decseq . 11)
(dec . 12)
($EOF . 13)
(EQARW . 14)
(RP . 15)
(IN . 16)
(EQ . 17)
(END . 18)
))

(setq rule-to-nonterminal [$start start exp exp appexp appexp atexp atexp atexp atexp atexp decseq decseq dec ])

(defun token-to-variable-name (token)
  (variable-name
   (cdr (assoc 'value token))
   (cdr (assoc 'left token))
   (cdr (assoc 'right token))))
  
(defun decseq-to-nested-let (decseq body)
  (if (eq decseq nil)
      body
    (exp-let (car (car decseq))
	     (car (cdr (car decseq)))
	     (decseq-to-nested-let (cdr decseq) body))))
    

(defun do-action (rule-number args)
  (cond 
    ((eq rule-number 0)
     ;;$start := start
     ;;here is not used
     )
    ((eq rule-number 1)
     ;;start := exp
     (get-value args 1))
    ((eq rule-number 2)
     ;;exp := appexp
     (get-value args 1))
    ((eq rule-number 3)
     ;;exp := FN ID EQARW exp
     (exp-abs (token-to-variable-name (get-value args 2))
	      (get-value args 4)))
    ((eq rule-number 4)
     ;;appexp := atexp
     (get-value args 1))
    ((eq rule-number 5)
     ;;appexp := appexp atexp
     (exp-app (get-value args 1) (get-value args 2)))
    ((eq rule-number 6)
     ;;atexp := ID
     (exp-var (token-to-variable-name (get-value args 1))))
    ((eq rule-number 7)
     ;;atexp := INT
     (exp-int (cdr (assoc 'value (get-value args 1)))))
    ((eq rule-number 8)
     ;;atexp := STRING
     (exp-str (cdr (assoc 'value (get-value args 1)))))
    ((eq rule-number 9)
     ;;atexp := LP exp RP
     (get-value args 2))
    ((eq rule-number 10)
     ;;atexp := LET decseq IN exp END
     (decseq-to-nested-let (get-value args 2)
			   (get-value args 4)))
    ((eq rule-number 11)
     ;;decseq := dec decseq
     (cons (get-value args 1) (get-value args 2)))
    ((eq rule-number 12)
     ;;decseq := 
    nil)
    ((eq rule-number 13)
     ;;dec := VAL ID EQ exp
     (list
      (token-to-variable-name (get-value args 2))
      (get-value args 4)))
))


(setq parser-table [
[
(shift . 16)
(shift . 17)
(shift . 18)
(shift . 8)
(shift . 1)
(shift . 6)
(goto . 9)
(goto . 19)
(goto . 5)
(goto . 20)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
]
[
(shift . 16)
(shift . 17)
(shift . 18)
(shift . 8)
(shift . 1)
(shift . 6)
(error . -1)
(goto . 11)
(goto . 5)
(goto . 20)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
]
[
(shift . 16)
(shift . 17)
(shift . 18)
(shift . 8)
(shift . 1)
(shift . 6)
(error . -1)
(goto . 24)
(goto . 5)
(goto . 20)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
]
[
(shift . 16)
(shift . 17)
(shift . 18)
(shift . 8)
(shift . 1)
(shift . 6)
(error . -1)
(goto . 15)
(goto . 5)
(goto . 20)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
]
[
(shift . 16)
(shift . 17)
(shift . 18)
(shift . 8)
(shift . 1)
(shift . 6)
(error . -1)
(goto . 25)
(goto . 5)
(goto . 20)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
]
[
(shift . 16)
(shift . 17)
(shift . 18)
(reduce . 2)
(shift . 1)
(shift . 6)
(reduce . 2)
(reduce . 2)
(reduce . 2)
(goto . 21)
(reduce . 2)
(reduce . 2)
(reduce . 2)
(reduce . 2)
(reduce . 2)
(reduce . 2)
(reduce . 2)
(reduce . 2)
(reduce . 2)
]
[
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(shift . 12)
(goto . 13)
(goto . 7)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
]
[
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(shift . 12)
(goto . 23)
(goto . 7)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
(reduce . 12)
]
[
(shift . 10)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
]
[
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(accept . $EOF)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
]
[
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(shift . 2)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
]
[
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(shift . 22)
(error . -1)
(error . -1)
(error . -1)
]
[
(shift . 14)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
]
[
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(shift . 3)
(error . -1)
(error . -1)
]
[
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(shift . 4)
(error . -1)
]
[
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(error . -1)
(shift . 26)
]
[
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
(reduce . 6)
]
[
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
(reduce . 7)
]
[
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
(reduce . 8)
]
[
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
(reduce . 1)
]
[
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
(reduce . 4)
]
[
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
(reduce . 5)
]
[
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
(reduce . 9)
]
[
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
(reduce . 11)
]
[
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
(reduce . 3)
]
[
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
(reduce . 13)
]
[
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
(reduce . 10)
]
])

(provide 'my-expr-parser-data)

