
(defun tokenizer-error-message (text)
  (message text))

(defun init-tokenizer ()
  (list
   (cons 'eof (point-max))
   (cons 'tokenizer-reached-eof  nil)
   (cons 'pos (point-min))
   (cons 'token nil)))

(defun token (symbol left right &optional value)
  (list 
   (cons 'symbol symbol)
   (cons 'value value)
   (cons 'left left)
   (cons 'right right)))

(defmacro define-tokenizer 
  (name conditions variables &rest rules)
  (defvar lexer-condition 'INITIAL
    "condition of tokenizer generated by macro define-tokenizer")
  ;;tokenizer init
  (let ((--dt-variables variables))
    (message (format "v:: %s" variables))
    (while (car --dt-variables)
      (if (not (listp (car --dt-variables)))
	  (set (car --dt-variables) nil)
	(set (car (car  --dt-variables)) (car (cdr (car --dt-variables)))))
      (setq --dt-variables (cdr --dt-variables))))
  (let ((process-list '())
	(rules rules)
	rule)
    ;;(message (format "rules::%s" rules))
    (while (car rules)
      (setq rule (car rules))
      ;;(message (format "rule::%s" rule))
      (setq process-list (cons
			  `((and 
				  (eq lexer-status (quote ,(car rule)))
				  ;;(message (format "checking:: %s" (car ',(cdr rule))))
				  (looking-at ,(car (cdr rule))))
			    (setq yypos (match-beginning 0))
			    (setq yytext (match-string-no-properties 0))
			    ,@(cdr (cdr rule)))
			  process-list))
      (setq rules (cdr rules)))
    (setq process-list (list (cons 'cond (reverse process-list))))
    ;;(print process-list)
    
    `(defun ,name (tokenizer &optional condition)
       ;;(message "tokenizer is called")
       (let ((lexer-rules ',rules)
	     yybegin yytext yypos (token nil)
	     (continue t) return 
	     (eof (cdr (assoc 'eof tokenizer)))
	     (lexer-status (if condition condition 'INITIAL)))
	 (goto-char (cdr (assoc 'pos tokenizer)))
	 (fset 'return (lambda (s l r &optional v) (setq token (token s l r v))))
	 (fset 'yybegin (lambda (status) (setq lexer-status status)))
	 (fset 'continue (lambda () (setq continue t) (goto-char (match-end 0))))
	 ;;(fset 'matched-text (lambda () (match-string-no-properties 0)));;(buffer-substring (match-beginning 0) (match-end 0))))
	 ;;(fset 'yypos (lambda () (match-beginning 0)))
	 ;;(message (format "continue:%s" continue))
	 ;;(message (format "eof:%s point:%s" eof (point)))
	 
	 (if (cdr (assoc 'tokenizer-reached-eof tokenizer))
	     (return '$EOF eof eof)
	   ;;(mes 1 (format "pos:%s, eof:%s" (point) eof))
	   (while (and 
		   continue 
		   (< (point) eof ))
	     (setq continue nil)
	     ,@process-list)
	   (setcdr (assoc 'pos tokenizer) (match-end 0))
	   
	   ;;cursor—v‘f
	   (when (>= (point) eof)
	     (setcdr (assoc 'tokenizer-reached-eof tokenizer) t)
	     (return '$EOF eof eof nil)))
	 token))))

(provide 'tokenizer-macro)