#!/usr/bin/perl --

use CGI;
use File::Copy;

$CGI::POST_MAX = 1024 * 1024 *10;
$query = new CGI;

print $query->header(-charset=>"utf-8");
print $query->start_html;

$file_handle_kihon1_1 = $query->upload("kihon1-1");
$file_handle_kihon1_2 = $query->upload("kihon1-2");
$file_handle_kihon2_1 = $query->upload("kihon2-1");
$file_handle_kihon2_2 = $query->upload("kihon2-2");
$file_handle_kihon3_1 = $query->upload("kihon3-1");
$file_handle_kihon3_2 = $query->upload("kihon3-2");
$file_handle_kihon4_1 = $query->upload("kihon4-1");
$file_handle_kihon4_2 = $query->upload("kihon4-2");
$file_handle_kihon5_1 = $query->upload("kihon5-1");
$file_handle_kihon5_2 = $query->upload("kihon5-2");
$file_handle_kihon6_1 = $query->upload("kihon6-1");
$file_handle_kihon6_2 = $query->upload("kihon6-2");
$file_handle_kihon7_1 = $query->upload("kihon7-1");
$file_handle_kihon7_2 = $query->upload("kihon7-2");
$file_handle_kihon8_1 = $query->upload("kihon8-1");
$file_handle_kihon8_2 = $query->upload("kihon8-2");
$file_handle_kihon10_1 = $query->upload("kihon10-1");
$file_handle_kihon10_2 = $query->upload("kihon10-2");
$file_handle_kihon11_1 = $query->upload("kihon11-1");
$file_handle_kihon11_2 = $query->upload("kihon11-2");
$file_handle_kihon12_1 = $query->upload("kihon12-1");
$file_handle_kihon12_2 = $query->upload("kihon12-2");
$file_handle_kihon13_1 = $query->upload("kihon13-1");
$file_handle_kihon13_2 = $query->upload("kihon13-2");
$file_handle_kihon13_3 = $query->upload("kihon13-3");

$file_handle_hatten1_1 = $query->upload("hatten1-1");
$file_handle_hatten1_2 = $query->upload("hatten1-2");
$file_handle_hatten2_1 = $query->upload("hatten2-1");
$file_handle_hatten2_2 = $query->upload("hatten2-2");
$file_handle_hatten3_1 = $query->upload("hatten3-1");
$file_handle_hatten3_2 = $query->upload("hatten3-2");
$file_handle_hatten3_3 = $query->upload("hatten3-3");
$file_handle_hatten3_4 = $query->upload("hatten3-4");
$file_handle_hatten4_1 = $query->upload("hatten4-1");
$file_handle_hatten4_2 = $query->upload("hatten4-2");
$file_handle_hatten4_3 = $query->upload("hatten4-3");
$file_handle_hatten5_1 = $query->upload("hatten5-1");
$file_handle_hatten5_2 = $query->upload("hatten5-2");
$file_handle_hatten5_3 = $query->upload("hatten5-3");
$file_handle_hatten5_4 = $query->upload("hatten5-4");
$file_handle_hatten6_1 = $query->upload("hatten6-1");
$file_handle_hatten6_2 = $query->upload("hatten6-2");
$file_handle_hatten6_3 = $query->upload("hatten6-3");
$file_handle_hatten6_4 = $query->upload("hatten6-4");
$file_handle_hatten7_1 = $query->upload("hatten7-1");
$file_handle_hatten7_2 = $query->upload("hatten7-2");
$file_handle_hatten7_3 = $query->upload("hatten7-3");
$file_handle_hatten7_4 = $query->upload("hatten7-4");
$file_handle_hatten7_5 = $query->upload("hatten7-5");
$file_handle_hatten8_1 = $query->upload("hatten8-1");
$file_handle_hatten8_2 = $query->upload("hatten8-2");
$file_handle_hatten8_3 = $query->upload("hatten8-3");
$file_handle_hatten8_4 = $query->upload("hatten8-4");
$file_handle_hatten10_1 = $query->upload("hatten10-1");
$file_handle_hatten10_2 = $query->upload("hatten10-2");
$file_handle_hatten10_3 = $query->upload("hatten10-3");
$file_handle_hatten11_1 = $query->upload("hatten11-1");
$file_handle_hatten11_2 = $query->upload("hatten11-2");
$file_handle_hatten12_1 = $query->upload("hatten12-1");
$file_handle_hatten12_2 = $query->upload("hatten12-2");
$file_handle_hatten12_3 = $query->upload("hatten12-3");
$file_handle_hatten12_4 = $query->upload("hatten12-4");
$file_handle_hatten13_1 = $query->upload("hatten13-1");
$file_handle_hatten13_2 = $query->upload("hatten13-2");
$file_handle_hatten13_3 = $query->upload("hatten13-3");
$file_handle_hatten13_4 = $query->upload("hatten13-4");

my $studentID = $query->param('studentID');

srand time;

my $randomname;
my $filename;

if($studentID){
    $filename = $studentID . "." . "c";
} else {
    $randomname = int(rand(100000000));
    $filename = $randomname . "." . "c";
}

$prefix = "/home/cs/pn2Files/";

$file_kihon1_1 = $prefix . "kihon1-1/" . $filename;
$file_kihon1_2 = $prefix . "kihon1-2/" . $filename;
$file_kihon2_1 = $prefix . "kihon2-1/" . $filename;
$file_kihon2_2 = $prefix . "kihon2-2/" . $filename;
$file_kihon3_1 = $prefix . "kihon3-1/" . $filename;
$file_kihon3_2 = $prefix . "kihon3-2/" . $filename;
$file_kihon4_1 = $prefix . "kihon4-1/" . $filename;
$file_kihon4_2 = $prefix . "kihon4-2/" . $filename;
$file_kihon5_1 = $prefix . "kihon5-1/" . $filename;
$file_kihon5_2 = $prefix . "kihon5-2/" . $filename;
$file_kihon6_1 = $prefix . "kihon6-1/" . $filename;
$file_kihon6_2 = $prefix . "kihon6-2/" . $filename;
$file_kihon7_1 = $prefix . "kihon7-1/" . $filename;
$file_kihon7_2 = $prefix . "kihon7-2/" . $filename;
$file_kihon8_1 = $prefix . "kihon8-1/" . $filename;
$file_kihon8_2 = $prefix . "kihon8-2/" . $filename;
$file_kihon10_1 = $prefix . "kihon10-1/" . $filename;
$file_kihon10_2 = $prefix . "kihon10-2/" . $filename;
$file_kihon11_1 = $prefix . "kihon11-1/" . $filename;
$file_kihon11_2 = $prefix . "kihon11-2/" . $filename;
$file_kihon12_1 = $prefix . "kihon12-1/" . $filename;
$file_kihon12_2 = $prefix . "kihon12-2/" . $filename;
$file_kihon13_1 = $prefix . "kihon13-1/" . $filename;
$file_kihon13_2 = $prefix . "kihon13-2/" . $filename;
$file_kihon13_3 = $prefix . "kihon13-3/" . $filename;

$file_hatten1_1 = $prefix . "hatten1-1/" . $filename;
$file_hatten1_2 = $prefix . "hatten1-2/" . $filename;
$file_hatten2_1 = $prefix . "hatten2-1/" . $filename;
$file_hatten2_2 = $prefix . "hatten2-2/" . $filename;
$file_hatten3_1 = $prefix . "hatten3-1/" . $filename;
$file_hatten3_2 = $prefix . "hatten3-2/" . $filename;
$file_hatten3_3 = $prefix . "hatten3-3/" . $filename;
$file_hatten3_4 = $prefix . "hatten3-4/" . $filename;
$file_hatten4_1 = $prefix . "hatten4-1/" . $filename;
$file_hatten4_2 = $prefix . "hatten4-2/" . $filename;
$file_hatten4_3 = $prefix . "hatten4-3/" . $filename;
$file_hatten5_1 = $prefix . "hatten5-1/" . $filename;
$file_hatten5_2 = $prefix . "hatten5-2/" . $filename;
$file_hatten5_3 = $prefix . "hatten5-3/" . $filename;
$file_hatten5_4 = $prefix . "hatten5-4/" . $filename;
$file_hatten6_1 = $prefix . "hatten6-1/" . $filename;
$file_hatten6_2 = $prefix . "hatten6-2/" . $filename;
$file_hatten6_3 = $prefix . "hatten6-3/" . $filename;
$file_hatten6_4 = $prefix . "hatten6-4/" . $filename;
$file_hatten7_1 = $prefix . "hatten7-1/" . $filename;
$file_hatten7_2 = $prefix . "hatten7-2/" . $filename;
$file_hatten7_3 = $prefix . "hatten7-3/" . $filename;
$file_hatten7_4 = $prefix . "hatten7-4/" . $filename;
$file_hatten7_5 = $prefix . "hatten7-5/" . $filename;
$file_hatten8_1 = $prefix . "hatten8-1/" . $filename;
$file_hatten8_2 = $prefix . "hatten8-2/" . $filename;
$file_hatten8_3 = $prefix . "hatten8-3/" . $filename;
$file_hatten8_4 = $prefix . "hatten8-4/" . $filename;
$file_hatten10_1 = $prefix . "hatten10-1/" . $filename;
$file_hatten10_2 = $prefix . "hatten10-2/" . $filename;
$file_hatten10_3 = $prefix . "hatten10-3/" . $filename;
$file_hatten11_1 = $prefix . "hatten11-1/" . $filename;
$file_hatten11_2 = $prefix . "hatten11-2/" . $filename;
$file_hatten12_1 = $prefix . "hatten12-1/" . $filename;
$file_hatten12_2 = $prefix . "hatten12-2/" . $filename;
$file_hatten12_3 = $prefix . "hatten12-3/" . $filename;
$file_hatten12_4 = $prefix . "hatten12-4/" . $filename;
$file_hatten13_1 = $prefix . "hatten13-1/" . $filename;
$file_hatten13_2 = $prefix . "hatten13-2/" . $filename;
$file_hatten13_3 = $prefix . "hatten13-3/" . $filename;
$file_hatten13_4 = $prefix . "hatten13-4/" . $filename;

copy ($file_handle_kihon1_1, $file_kihon1_1);
copy ($file_handle_kihon1_2, $file_kihon1_2);
copy ($file_handle_kihon2_1, $file_kihon2_1);
copy ($file_handle_kihon2_2, $file_kihon2_2);
copy ($file_handle_kihon3_1, $file_kihon3_1);
copy ($file_handle_kihon3_2, $file_kihon3_2);
copy ($file_handle_kihon4_1, $file_kihon4_1);
copy ($file_handle_kihon4_2, $file_kihon4_2);
copy ($file_handle_kihon5_1, $file_kihon5_1);
copy ($file_handle_kihon5_2, $file_kihon5_2);
copy ($file_handle_kihon6_1, $file_kihon6_1);
copy ($file_handle_kihon6_2, $file_kihon6_2);
copy ($file_handle_kihon7_1, $file_kihon7_1);
copy ($file_handle_kihon7_2, $file_kihon7_2);
copy ($file_handle_kihon8_1, $file_kihon8_1);
copy ($file_handle_kihon8_2, $file_kihon8_2);
copy ($file_handle_kihon10_1, $file_kihon10_1);
copy ($file_handle_kihon10_2, $file_kihon10_2);
copy ($file_handle_kihon11_1, $file_kihon11_1);
copy ($file_handle_kihon11_2, $file_kihon11_2);
copy ($file_handle_kihon12_1, $file_kihon12_1);
copy ($file_handle_kihon12_2, $file_kihon12_2);
copy ($file_handle_kihon13_1, $file_kihon13_1);
copy ($file_handle_kihon13_2, $file_kihon13_2);
copy ($file_handle_kihon13_3, $file_kihon13_3);

copy ($file_handle_hatten1_1, $file_hatten1_1);
copy ($file_handle_hatten1_2, $file_hatten1_2);
copy ($file_handle_hatten2_1, $file_hatten2_1);
copy ($file_handle_hatten2_2, $file_hatten2_2);
copy ($file_handle_hatten3_1, $file_hatten3_1);
copy ($file_handle_hatten3_2, $file_hatten3_2);
copy ($file_handle_hatten3_3, $file_hatten3_3);
copy ($file_handle_hatten3_4, $file_hatten3_4);
copy ($file_handle_hatten4_1, $file_hatten4_1);
copy ($file_handle_hatten4_2, $file_hatten4_2);
copy ($file_handle_hatten4_3, $file_hatten4_3);
copy ($file_handle_hatten5_1, $file_hatten5_1);
copy ($file_handle_hatten5_2, $file_hatten5_2);
copy ($file_handle_hatten5_3, $file_hatten5_3);
copy ($file_handle_hatten5_4, $file_hatten5_4);
copy ($file_handle_hatten6_1, $file_hatten6_1);
copy ($file_handle_hatten6_2, $file_hatten6_2);
copy ($file_handle_hatten6_3, $file_hatten6_3);
copy ($file_handle_hatten6_4, $file_hatten6_4);
copy ($file_handle_hatten7_1, $file_hatten7_1);
copy ($file_handle_hatten7_2, $file_hatten7_2);
copy ($file_handle_hatten7_3, $file_hatten7_3);
copy ($file_handle_hatten7_4, $file_hatten7_4);
copy ($file_handle_hatten7_5, $file_hatten7_5);
copy ($file_handle_hatten8_1, $file_hatten8_1);
copy ($file_handle_hatten8_2, $file_hatten8_2);
copy ($file_handle_hatten8_3, $file_hatten8_3);
copy ($file_handle_hatten8_4, $file_hatten8_4);
copy ($file_handle_hatten10_1, $file_hatten10_1);
copy ($file_handle_hatten10_2, $file_hatten10_2);
copy ($file_handle_hatten10_3, $file_hatten10_3);
copy ($file_handle_hatten11_1, $file_hatten11_1);
copy ($file_handle_hatten11_2, $file_hatten11_2);
copy ($file_handle_hatten12_1, $file_hatten12_1);
copy ($file_handle_hatten12_2, $file_hatten12_2);
copy ($file_handle_hatten12_3, $file_hatten12_3);
copy ($file_handle_hatten12_4, $file_hatten12_4);
copy ($file_handle_hatten13_1, $file_hatten13_1);
copy ($file_handle_hatten13_2, $file_hatten13_2);
copy ($file_handle_hatten13_3, $file_hatten13_3);
copy ($file_handle_hatten13_4, $file_hatten13_4);

print "ありがとうございました。";
print $query->end_html;
exit;
